// Port Harcourt Cities/Areas for location dropdown
export const PORTHARCOURT_LOCATIONS = [
  { value: '', label: 'Select your location' },
  { value: 'Ada-George', label: 'Ada-George' },
  { value: 'Aluu', label: 'Aluu' },
  { value: 'Amadi-Ama', label: 'Amadi-Ama' },
  { value: 'Bori', label: 'Bori' },
  { value: 'Choba', label: 'Choba' },
  { value: 'D-Line', label: 'D-Line' },
  { value: 'Dakata', label: 'Dakata' },
  { value: 'Elekahia', label: 'Elekahia' },
  { value: 'Elelenwo', label: 'Elelenwo' },
  { value: 'Eliopoly', label: 'Eliopoly' },
  { value: 'Elito', label: 'Elito' },
  { value: 'Eneka', label: 'Eneka' },
  { value: 'Iwofe', label: 'Iwofe' },
  { value: 'Kaa', label: 'Kaa' },
  { value: 'Ketu', label: 'Ketu' },
  { value: 'MGbada', label: 'MGbada' },
  { value: 'Milling Plant', label: 'Milling Plant' },
  { value: 'Nego', label: 'Nego' },
  { value: 'New GRA', label: 'New GRA' },
  { value: 'Nkpolu', label: 'Nkpolu' },
  { value: 'Obu-Obele', label: 'Obu-Obele' },
  { value: 'Ogbunike', label: 'Ogbunike' },
  { value: 'Oginigba', label: 'Oginigba' },
  { value: 'Oi', label: 'Oi' },
  { value: 'Okporowo', label: 'Okporowo' },
  { value: 'Omagwa', label: 'Omagwa' },
  { value: 'Omoku', label: 'Omoku' },
  { value: 'Orji', label: 'Orji' },
  { value: 'Oyigbo', label: 'Oyigbo' },
  { value: 'Pirri', label: 'Pirri' },
  { value: 'Rumuaghaolu', label: 'Rumuaghaolu' },
  { value: 'Rumuakpani', label: 'Rumuakpani' },
  { value: 'Rumuibekwe', label: 'Rumuibekwe' },
  { value: 'Rumuigbo', label: 'Rumuigbo' },
  { value: 'Rumuita', label: 'Rumuita' },
  { value: 'Rumuodumaya', label: 'Rumuodumaya' },
  { value: 'Rumuokwachi', label: 'Rumuokwachi' },
  { value: 'Rumuola', label: 'Rumuola' },
  { value: 'Rumuoside', label: 'Rumuoside' },
  { value: 'Rumu-pi', label: 'Rumu-pi' },
  { value: 'Rumu-ti', label: 'Rumu-ti' },
  { value: 'Sugar', label: 'Sugar' },
  { value: 'Tombia', label: 'Tombia' },
  { value: 'Trans-Amadi', label: 'Trans-Amadi' },
  { value: 'Woji', label: 'Woji' },
  { value: 'YKC', label: 'YKC' },
  { value: 'Other', label: 'Other' }
]

export default PORTHARCOURT_LOCATIONS